/***
* Combodef.ch
*
* Definition of translates for simulated Combo box class
*/

// #translates for drop get pseudo sub-class
#translate :comboItems  => :cargo\[1\]
#translate :comboTop    => :cargo\[2\]
#translate :comboLeft   => :cargo\[3\]
#translate :comboBottom => :cargo\[4\]
#translate :comboRight  => :cargo\[5\]
#translate :comboColors => :cargo\[6\]
#translate :readonly    => :cargo\[7\]
#define COMBO_NUM_IVARS 7
