// color definitions
#define BLACK    "N"
#define BLUE     "B"
#define GREEN    "G"
#define CYAN     "BG"
#define RED      "R"
#define MAGENTA  "RB"
#define BROWN    "GR"
#define WHITE    "W"
#define GRAY     "N+"
#define BBLUE    "B+"
#define BGREEN   "G+"
#define BCYAN    "BG+"
#define BRED     "R+"
#define BMAGENTA "RB+"
#define YELLOW  "GR+"
#define BWHITE   "W+"


#xtranslate CFB(<forg>,<bacg>) => <forg>+"/"+<bacg>
